server:
  port: 8763
spring:
  application:
    name: user-service-8763 #服务名
  profiles:
    active: company
#负载
ribbon:
  ReadTimeout:  10000
  ConnectTimeout:  10000
  MaxAutoRetries: 0   # 最大重试次数，默认0
  MaxAutoRetriesNextServer: 1  # 最大重试服务个数，默认1
#熔断器参数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
#Sql日志输出
logging:
  level:
    com.de.providerserverdemo.dao: debug
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN