server:
  port: 8765
spring:
  application:
    name: provider-service-demo #服务名
  zipkin: #链路跟踪
    base-url: http://localhost:9411
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      percentage: 1.0 # 设置zipkin采样比例  默认0.1
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/    #注册中心地址
