server:
  port: 8765
spring:
  application:
    name: provider-service-demo #服务名
  profiles:
    active: company  #选择加载不同环境的yml文件
#负载
ribbon:
  ReadTimeout:  10000
  ConnectTimeout:  10000
  MaxAutoRetries: 0   # 最大重试次数，默认0
  MaxAutoRetriesNextServer: 1  # 最大重试服务个数，默认1
#熔断器参数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
