server:
  port: 8771
  servlet:
    session:
      timeout: 30m # session会话超时时间，默认情况 下是30分钟（m）,不能小于1分钟
      cookie:
        name: JSESSIONID_CLD # 指定浏览器Cookie中关于SessionID保存的那个名称
spring:
  application:
    name: security-oauth-demo
  datasource: #数据库
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##lmh
    password: 123456
  redis: #redis
    host: localhost
    port: 6379
  session:
    store-type: redis  #使用redis存储session数据
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #注册中心地址
#开启hystrix配置
feign:
  hystrix:
    enabled: true #开启熔断机制
#负载
ribbon:
  ReadTimeout:  10000
  ConnectTimeout:  10000
  MaxAutoRetries: 0   # 最大重试次数，默认0
  MaxAutoRetriesNextServer: 1  # 最大重试服务个数，默认1
#熔断器参数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

cis:
  security:
    authentication: #授权相关
      #表单认证
      loginPage: /login/page #登录页面
      loginProcessingUrl: /login/form #登录提交处理
      usernameParameter: name #用户名属性名称
      passwordParameter: pwd #密码属性名称
      defaultSuccessUrl: /hello #登录成功处理
      apiAntMatchers:  #免认证接口 ，数组用-
      - /login/**
      loginHandlerType: REDIRECT #认证之后的处理方式