#端口  服务名
server:
  port: 8766
spring:
  application:
    name: zuul-server-demo
  zipkin: #链路跟踪
    base-url: http://localhost:9411
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      percentage: 1.0 # 设置zipkin采样比例  默认0.1
#注册中心
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
#网关
zuul:
  routes:
    #标识服务名，用于拦截请求  服务转发
    #  1
    consumerServiceDemo:
      path: /consumerServiceDemo/**
      serviceId: consumer-service-demo

    #  2....
